import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import Navigation from "@/components/navigation";
import { getCategoryLinks } from "./actions/getCategories";
import MarketFetcher from "@/components/market-fetcher";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategoryLinks();

  return (
    <html lang="en" className={figtree.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navigation categories={categories} />
          <div className="max-w-360 mx-auto grid grid-cols-1 lg:grid-cols-[280px_1fr_320px] gap-8 px-4">
            <aside className="hidden lg:block">
              <div className="sticky top-20 h-[calc(100vh-5rem)] overflow-y-auto py-8">
                <p className="text-sm font-semibold mb-4 uppercase tracking-wider text-muted-foreground">
                  Market
                </p>
                <MarketFetcher />
              </div>
            </aside>

            <main className="py-8 min-w-0">{children}</main>

            <aside className="hidden xl:block">
              <div className="sticky top-20 h-[calc(100vh-5rem)] overflow-y-auto py-8">
                <p className="text-sm font-semibold mb-4 uppercase tracking-wider text-muted-foreground">
                  Weather
                </p>
                Right Sidebar Widgets Go Here
              </div>
            </aside>
          </div>
        </Providers>
      </body>
    </html>
  );
}
