import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import Navigation from "@/components/navigation";
import { getCategoryLinks } from "./actions/getCategories";
import MarketFetcher from "@/components/market-fetcher";
import WeatherWidget from "@/components/weather-component";
import { SidebarSheets } from "@/components/sidebar-sheets";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategoryLinks();

  return (
    <html lang="en" className={figtree.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navigation categories={categories} />
          <SidebarSheets
            marketContent={<MarketFetcher />}
            weatherContent={<WeatherWidget />}
          />
          <div className="max-w-400 mx-auto grid grid-cols-1 lg:grid-cols-[minmax(220px,300px)_1fr_minmax(220px,300px)] gap-5 px-4">
            <aside className="hidden lg:block">
              <div className="sticky top-20 h-[calc(100vh-5rem)] overflow-y-auto py-8 text-left">
                <p className="text-sm font-semibold mb-6 uppercase tracking-wider text-muted-foreground font-sans">
                  Market Watch
                </p>
                <MarketFetcher />
              </div>
            </aside>

            <main className="min-w-0 lg:min-w-125 pb-20">{children}</main>

            <aside className="hidden lg:block">
              <div className="sticky top-20 h-[calc(100vh-5rem)] overflow-y-auto py-8 text-left">
                <p className="text-sm font-semibold mb-6 uppercase tracking-wider text-muted-foreground font-sans">
                  Weather Forecast
                </p>
                <WeatherWidget />
              </div>
            </aside>
          </div>
        </Providers>
      </body>
    </html>
  );
}
